[package]
name = "stun-message"
version = "0.1.0"
authors = ["Nathan Buckles <nbuckles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.1"
nom = "5.0"
